version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-quiz-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - faiss_index:/app/faiss_index
      - uploaded_files:/app/uploaded_files
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ main port
      - "15672:15672"   # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  faiss_index:
  uploaded_files:
  rabbitmq_data:
